import type { Industry } from "./types";

export const industries: Industry[] = [
  {
    slug: "manufacturing",
    name: "Manufacturing",
    short: "Discrete manufacturing and job shops",
    title: "Industrial IoT & Automation for Manufacturing",
    description:
      "Machine monitoring, automation and industrial IoT for discrete manufacturing — OEE, downtime capture and production visibility on mixed, existing machinery.",
    h1: "Manufacturing",
    lead: "Discrete manufacturing plants usually have the widest machine mix of any sector — presses, CNCs, welders, assembly stations and packing lines from a dozen makers and four decades. That mix is exactly why visibility is hard, and exactly why a retrofit approach matters more here than anywhere else.",
    problems: [
      "Output is counted manually and reconciled the next day",
      "The stated bottleneck is based on opinion rather than measurement",
      "Micro-stops are invisible but cumulatively larger than the recorded stoppages",
      "Changeover time varies by hours depending on who runs it",
      "Every machine is a different brand with a different interface and no common data",
    ],
    solutions: [
      { title: "Machine monitoring across mixed equipment", body: "Automatic state and count capture from any machine — via its PLC where one exists, via current and proximity sensing where it does not — normalised into one model." },
      { title: "Downtime and reason capture", body: "Stops detected automatically, reasons captured by the operator in seconds, and Pareto analysis that shows where the time actually goes." },
      { title: "OEE with defensible numbers", body: "Availability, performance and quality tracked separately with documented assumptions, so the figure survives scrutiny in a review meeting." },
      { title: "Line and cell automation", body: "Sequencing, interlocking and integration between machines that currently run independently." },
      { title: "Production tracking software", body: "Work orders, schedule adherence and actual-versus-plan driven by machine data rather than by status updates." },
    ],
    technology: [
      "PLC tag reads from Siemens, Allen-Bradley, Mitsubishi, Delta",
      "Current transformers for state detection on unmanaged machines",
      "Proximity and photoelectric counters",
      "Energy meters per machine or feeder",
      "Shop-floor tablets for reason codes and changeover",
      "Time-series database with per-machine, per-shift, per-product context",
    ],
    outcomes: [
      "The real constraint becomes measurable rather than debated",
      "Short stops become visible for the first time",
      "Shift and machine comparison on a like-for-like basis",
      "Changeover variation exposed and reducible",
      "Production reporting that no longer requires manual assembly",
    ],
    services: ["machine-monitoring", "industrial-iot", "industrial-automation", "industrial-dashboards", "plc-programming"],
    faq: [
      { q: "We have twelve machines from eight makers. Can they all be monitored?", a: "Yes, and this is the normal case rather than the difficult one. Machines with a controller are read over their native protocol; machines without one are instrumented externally with a current transformer and a counting sensor. All of it is normalised into a single model, so the dashboard does not care what brand a machine is." },
      { q: "What is the smallest sensible first project?", a: "One line or three to five machines, typically live within a few weeks. That is enough to prove the data, get operators used to reason codes, and produce genuine findings — while being small enough that a wrong assumption is cheap to correct." },
    ],
  },

  {
    slug: "automotive",
    name: "Automotive",
    short: "Tier 1, Tier 2 and component suppliers",
    title: "Industrial Automation & IoT for Automotive Suppliers",
    description:
      "Automation, traceability and machine monitoring for automotive component manufacturers — OEM data requirements, part-level traceability and line efficiency.",
    h1: "Automotive components",
    lead: "Automotive suppliers face demands that most sectors do not: part-level traceability, customer audits, data submissions to the OEM, and takt times that make a few seconds of variation matter. Meanwhile the same plant often runs machinery bought over thirty years.",
    problems: [
      "OEM customers require traceability and data the plant cannot currently produce",
      "Audit preparation consumes weeks and depends on manual record assembly",
      "Rejection causes are identified after the fact, not at the process",
      "Takt-time variation is felt but not measured",
      "Data must be produced per part, but production is only recorded per shift",
    ],
    solutions: [
      { title: "Part and batch traceability", body: "Serial or batch-level genealogy linking material, machine, process parameters, operator and quality result — queryable in minutes rather than reconstructed over days." },
      { title: "Process parameter logging", body: "Continuous capture of the process conditions that produced each part, so a quality problem can be traced to a cause instead of a shift." },
      { title: "Cycle-time and takt monitoring", body: "Per-station cycle measurement with variation and balance made visible across the line." },
      { title: "Poka-yoke and interlock integration", body: "Error-proofing tied into the control system so a miss becomes a stop, not a rejection found downstream." },
      { title: "Audit-ready reporting", body: "Records maintained continuously with defined retention, so an audit is a query rather than a project." },
    ],
    technology: [
      "Barcode, QR and DMC marking and reading",
      "Torque, force and vision system integration",
      "PLC and robot data capture",
      "Ethernet/IP and Profinet on modern lines; Modbus on older cells",
      "Relational genealogy database with parameter history",
      "APIs for customer and OEM data submission",
    ],
    outcomes: [
      "Traceability queries answered in minutes",
      "Process conditions attached to every part or batch",
      "Cycle-time variation visible per station",
      "Audit evidence maintained continuously rather than assembled",
      "Rejection causes traceable to process rather than to shift",
    ],
    services: ["machine-monitoring", "custom-industrial-software", "industrial-automation", "plc-programming", "system-integration"],
    faq: [
      { q: "Our OEM customer requires specific data submissions. Can you support that?", a: "Yes — provided the required format is specified, which it normally is. The engineering task is usually capturing the underlying data reliably rather than the submission itself, and we design the capture around the submission requirement from the start." },
      { q: "Can traceability be retrofitted to an existing line?", a: "Usually yes, though it depends on whether parts can be uniquely identified at the points that matter. Where marking does not exist, adding it is often the first step. We assess that during the survey and are direct about where genuine part-level traceability is achievable and where only batch-level is realistic." },
    ],
  },

  {
    slug: "pharmaceutical",
    name: "Pharmaceutical",
    short: "Formulation, API and packaging",
    title: "Automation & Monitoring for Pharmaceutical Manufacturing",
    description:
      "SCADA, monitoring and data integrity for pharmaceutical manufacturing — environmental monitoring, batch records, audit trails and validated system support.",
    h1: "Pharmaceutical manufacturing",
    lead: "In pharmaceutical manufacturing the data is part of the product. Records must be attributable, legible, contemporaneous, original and accurate — which changes how every system is designed, from the audit trail up. We work to that standard rather than adding it afterwards.",
    problems: [
      "Environmental monitoring recorded manually on rounds",
      "Batch records assembled from several systems and paper",
      "Audit trail requirements not met by existing tools",
      "Deviations identified during review rather than as they occur",
      "Validated systems make change slow, so improvements are deferred indefinitely",
    ],
    solutions: [
      { title: "Continuous environmental monitoring", body: "Temperature, humidity, differential pressure and particle counts logged continuously with alarms, escalation and a complete audit trail." },
      { title: "Electronic batch records", body: "Process parameters, equipment, materials, operators and results captured against the batch as it runs, with electronic signature support." },
      { title: "Data integrity by design", body: "Immutable audit logging, role-based access, time synchronisation and controlled change — designed in from the start because retrofitting it is far harder." },
      { title: "Equipment and utility monitoring", body: "Autoclaves, HVAC, purified water and compressed air monitored continuously with excursion alerting." },
      { title: "Validation support", body: "Documentation, test protocols and traceability matrices prepared to support your qualification and validation activities." },
    ],
    technology: [
      "Calibrated sensors with documented traceability",
      "SCADA platforms with audit trail and signature support",
      "Time-synchronised logging across all systems",
      "Role-based access with segregation of duties",
      "Immutable, queryable audit storage",
      "Structured documentation for IQ/OQ/PQ support",
    ],
    outcomes: [
      "Environmental excursions detected as they happen, not at review",
      "Batch record assembly time substantially reduced",
      "Audit trail available to inspection without preparation",
      "Utility performance monitored continuously",
      "Change managed within a controlled, documented process",
    ],
    services: ["scada-development", "machine-monitoring", "custom-industrial-software", "system-integration", "industrial-iot"],
    faq: [
      { q: "Do you provide validated systems?", a: "We design and build systems to support validation, and we prepare the documentation, test protocols and traceability that qualification requires. Validation itself is executed and approved by your quality function — that is how it should work, and any vendor claiming to hand you a pre-validated system is describing something different from what your regulator means." },
      { q: "How do you handle 21 CFR Part 11 and Annex 11 expectations?", a: "Through the technical controls those expectations require: unique user identity, role-based access, secure electronic signature where applicable, immutable and reviewable audit trails, time synchronisation, and controlled change management. We map each control to the requirement in the design documentation so your quality team can review it directly." },
    ],
  },

  {
    slug: "food-and-beverage",
    name: "Food & Beverage",
    short: "Processing, dairy, bakery and bottling",
    title: "Automation & Monitoring for Food & Beverage Plants",
    description:
      "Industrial automation and monitoring for food and beverage manufacturing — process control, cold chain monitoring, CIP verification and traceability.",
    h1: "Food & beverage",
    lead: "Food plants combine continuous process control, hygiene requirements, short shelf lives and traceability obligations. They also run hard, with limited windows for anything that touches production — which makes retrofit and phased work the only practical approach.",
    problems: [
      "Temperature excursions discovered after product is affected",
      "CIP cycles assumed to be effective rather than verified and recorded",
      "Traceability from raw material to despatch is manual and slow",
      "Giveaway on fill weight is known to exist but not quantified",
      "Changeover and cleaning time is a large, unmeasured share of the day",
    ],
    solutions: [
      { title: "Cold chain and process temperature monitoring", body: "Continuous logging across storage, process and despatch with alerting and an auditable record." },
      { title: "CIP verification and recording", body: "Time, temperature, concentration and flow recorded per cycle, so cleaning is evidenced rather than assumed." },
      { title: "Batch traceability", body: "Raw material to finished goods genealogy with the process conditions attached, making a recall query fast and bounded." },
      { title: "Filling and weight control", body: "Checkweigher and filler integration with statistical control, so giveaway becomes visible and controllable." },
      { title: "Line efficiency monitoring", body: "Downtime, changeover and cleaning time measured separately, because they have completely different improvement paths." },
    ],
    technology: [
      "Hygienic temperature, flow, pressure and conductivity instrumentation",
      "PLC and SCADA for process sequencing and CIP",
      "Checkweigher and filler integration",
      "Batch genealogy database",
      "Continuous logging with alarm escalation",
      "Reporting for customer and regulatory audit",
    ],
    outcomes: [
      "Temperature excursions caught while product can still be protected",
      "CIP effectiveness evidenced with a per-cycle record",
      "Recall scope determinable in minutes",
      "Fill giveaway quantified and reducible",
      "Cleaning and changeover time measured rather than estimated",
    ],
    services: ["industrial-automation", "scada-development", "machine-monitoring", "industrial-iot", "custom-industrial-software"],
    faq: [
      { q: "Can monitoring be installed in a wash-down area?", a: "Yes, with appropriately rated instrumentation and enclosures — typically IP66 or above, hygienic mountings, and cable entries designed for wash-down. This is a specification question rather than an obstacle; the cost difference is real but modest." },
      { q: "We have very little downtime available for installation. Is that workable?", a: "It is the normal constraint in this sector. Most of our installation work in food plants happens during cleaning windows and planned maintenance, in short phases. We plan the work so each phase is independently complete and the line is production-ready at the end of every window." },
    ],
  },

  {
    slug: "textile",
    name: "Textile",
    short: "Spinning, weaving, processing and garments",
    title: "Machine Monitoring & Automation for Textile Mills",
    description:
      "Machine monitoring and automation for textile manufacturing — loom and spindle monitoring, production tracking, energy per kilogram and process control.",
    h1: "Textile manufacturing",
    lead: "Textile mills run large numbers of similar machines, continuously, in energy-intensive processes. That combination makes per-machine visibility unusually valuable: small differences repeated across hundreds of machines and thousands of hours become very large numbers.",
    problems: [
      "Machine efficiency reported per shed rather than per machine",
      "Stoppages and breaks recorded by rounds rather than continuously",
      "Energy is a major cost with no attribution to machine or product",
      "Quality issues traced back to a shift at best, never to a machine",
      "Doffing, changeover and maintenance time is unmeasured",
    ],
    solutions: [
      { title: "Per-machine production monitoring", body: "Efficiency, output and stoppage per loom, frame or spindle set, measured continuously rather than sampled on rounds." },
      { title: "Energy per unit produced", body: "Consumption attributed by machine, shift and product, revealing which assets and which product mixes are genuinely expensive." },
      { title: "Process parameter monitoring", body: "Temperature, humidity, tension and speed logged continuously, connecting process conditions to quality outcomes." },
      { title: "Utility and plant monitoring", body: "Compressors, humidification and chillers monitored, which in this sector is frequently the largest single recoverable loss." },
      { title: "Shed-level and mill-level dashboards", body: "Live comparison across machines and sheds, with drill-down to the individual machine and shift." },
    ],
    technology: [
      "Machine controller reads where available; sensor retrofit where not",
      "Current transformers for state and load detection",
      "Energy meters per machine, section or feeder",
      "Temperature and humidity sensing for process areas",
      "Large-format shed displays for live efficiency",
      "Long-retention time-series storage for seasonal comparison",
    ],
    outcomes: [
      "Machine-level efficiency comparison across the mill",
      "Energy cost attributable to machine and product",
      "Stoppage patterns visible per machine rather than per shed",
      "Utility losses, especially compressed air, made visible",
      "Maintenance prioritised by measured performance",
    ],
    services: ["machine-monitoring", "industrial-iot", "predictive-maintenance", "industrial-dashboards", "edge-computing"],
    faq: [
      { q: "We have three hundred looms. Is monitoring all of them practical?", a: "Yes, and the per-machine cost falls considerably at that scale because the design work is done once and replicated. We would normally prove it on one shed first, then roll out — both to validate the approach and because the first shed always teaches you something about the rollout." },
      { q: "Our machines are quite old. Does that rule this out?", a: "No. Age is rarely the obstacle; the question is whether the machine exposes anything electrically. Almost all do — a motor to sense current on, a moving element to count, a drive to read. Machines from the 1980s are monitored routinely." },
    ],
  },

  {
    slug: "packaging",
    name: "Packaging",
    short: "Converting, printing, filling and labelling",
    title: "Automation & Monitoring for Packaging Lines",
    description:
      "Automation and machine monitoring for packaging lines — line efficiency, changeover reduction, waste tracking and integration across mixed-vendor equipment.",
    h1: "Packaging",
    lead: "Packaging lines are sequences of machines from different makers that must behave as one system. Most of the loss on such a line is not in any single machine — it is in the interactions between them, and in changeovers that nobody has ever timed properly.",
    problems: [
      "The line stops constantly for short periods that are never recorded",
      "Every machine is a different brand with a different interface",
      "Changeovers take unpredictable time with no measured baseline",
      "Material waste is known in total but not by cause",
      "Nobody can say which machine is actually pacing the line",
    ],
    solutions: [
      { title: "Whole-line monitoring", body: "State and count captured at every station, so blocking, starving and the true constraint become visible rather than argued about." },
      { title: "Micro-stop analysis", body: "Short stops measured and categorised, which on packaging lines almost always turns out to be the largest single loss." },
      { title: "Changeover measurement and guidance", body: "Changeovers timed automatically and supported with guided sequences and enforced parameters on the HMI." },
      { title: "Waste and reject tracking", body: "Rejects captured by cause and by station, tied to the process conditions at the time." },
      { title: "Cross-vendor line integration", body: "Handshaking and coordination between machines that currently run as independent islands." },
    ],
    technology: [
      "PLC reads across mixed vendors, normalised to one model",
      "Photoelectric and proximity counting at each station",
      "Checkweigher, labeller and coder integration",
      "HMI-based changeover guidance and reason capture",
      "Line-level dashboards showing blocking and starving",
      "Historical analysis by product, shift and crew",
    ],
    outcomes: [
      "The true line constraint identified from measurement",
      "Micro-stop losses quantified for the first time",
      "Changeover duration and variation measured",
      "Waste attributable to station and cause",
      "One view across machines from different vendors",
    ],
    services: ["machine-monitoring", "industrial-automation", "hmi-development", "plc-programming", "industrial-dashboards"],
    faq: [
      { q: "Our line has six machines from six vendors. Is that a problem?", a: "It is the usual situation and it is what the edge layer exists to solve. Each machine is read over whatever it supports, and everything is normalised into one model — so the line-level view does not care that station three is Italian and station four is Japanese." },
      { q: "What usually turns out to be the biggest loss?", a: "In our experience of packaging lines, micro-stops — the repeated short stoppages that are individually too brief to record manually and collectively larger than the recorded downtime. They are effectively invisible without automatic capture, which is why measuring them first is usually the highest-value step." },
    ],
  },

  {
    slug: "chemical",
    name: "Chemical",
    short: "Process, specialty and intermediates",
    title: "Process Automation & SCADA for Chemical Plants",
    description:
      "Process automation, SCADA and monitoring for chemical manufacturing — batch control, alarm rationalisation, safety coordination and environmental compliance.",
    h1: "Chemical & process",
    lead: "Chemical plants are continuous or batch processes where the control system is central rather than supporting, and where alarm quality has a direct relationship with safety. The engineering standard here is higher, and the consequences of getting it wrong are not commercial.",
    problems: [
      "Alarm floods during upsets, causing operators to ignore alarms generally",
      "Batch records assembled manually from several sources",
      "Process conditions logged but never analysed for yield or quality correlation",
      "Environmental parameters reported periodically rather than monitored continuously",
      "SCADA running on an unsupported operating system with no upgrade path defined",
    ],
    solutions: [
      { title: "Alarm rationalisation", body: "Every alarm justified by consequence and required action, with priorities and deadbands set to eliminate chatter. Usually the highest-value improvement available on an existing system." },
      { title: "Batch and recipe control", body: "Recipe-driven sequencing with parameter enforcement and a complete, automatically assembled batch record." },
      { title: "SCADA modernisation", body: "Migration from unsupported platforms with history preserved and cut-over phased area by area." },
      { title: "Environmental and emissions monitoring", body: "Continuous monitoring with alerting and reporting suitable for regulatory submission." },
      { title: "Process data analysis", body: "Yield, quality and energy correlated against process conditions, which is where the improvement opportunities in a stable process usually are." },
    ],
    technology: [
      "SCADA and DCS integration",
      "Batch control structured to ISA-88 concepts where appropriate",
      "Historian design for process trend analysis",
      "Coordination with safety instrumented systems, engineered by a qualified safety engineer",
      "Continuous emissions and effluent monitoring",
      "Segmented OT network architecture",
    ],
    outcomes: [
      "Alarm rate reduced to a level operators can act on",
      "Batch records assembled automatically",
      "Process history usable for yield and quality investigation",
      "Environmental reporting produced from continuous data",
      "A supported, maintainable supervisory platform",
    ],
    services: ["scada-development", "industrial-automation", "edge-computing", "predictive-maintenance", "system-integration"],
    faq: [
      { q: "Do you work on safety instrumented systems?", a: "We coordinate with them; we do not design or certify safety functions unless the engagement explicitly includes a qualified functional safety engineer. The basic process control system and the safety system must be independent, and we design to preserve that independence. We are explicit about this boundary before contracting rather than during commissioning." },
      { q: "How much difference does alarm rationalisation actually make?", a: "On systems that have never had it, a great deal. Plants commonly run at alarm rates far above what a person can process, which means the alarm system has stopped functioning as a safety layer. Rationalisation is largely engineering analysis rather than new equipment, so it is also one of the least capital-intensive improvements available." },
    ],
  },

  {
    slug: "energy-and-utilities",
    name: "Energy & Utilities",
    short: "Generation, distribution and captive power",
    title: "Monitoring & Automation for Energy and Utilities",
    description:
      "Monitoring and automation for energy and utilities — captive power, solar generation, substations and distributed asset monitoring with remote visibility.",
    h1: "Energy & utilities",
    lead: "Energy assets are frequently distributed, often unmanned, and usually monitored by someone driving to them. Remote visibility changes the economics of operating them — and the engineering problem is less about sensors than about reliable communication from places with poor connectivity.",
    problems: [
      "Distributed assets require physical visits to check status",
      "Faults are discovered by a customer complaint or a bill, not by the system",
      "Generation performance is compared against expectation only monthly",
      "Data from different vendors' equipment cannot be viewed together",
      "Sites have unreliable connectivity, so remote systems have gaps",
    ],
    solutions: [
      { title: "Remote asset monitoring", body: "Continuous status, output and fault reporting from distributed sites, with alerting and escalation." },
      { title: "Generation performance analysis", body: "Actual versus expected output normalised for conditions, so underperformance is detected in days rather than at month end." },
      { title: "Substation and switchgear monitoring", body: "Electrical parameters, breaker status and transformer condition, integrated across vendors." },
      { title: "Energy accounting", body: "Consumption and generation reconciled by site, feeder and time of day, with cost attribution." },
      { title: "Resilient communications", body: "Cellular with local buffering and store-and-forward, designed so an outage is a transmission gap and not a data gap." },
    ],
    technology: [
      "IEC 61850 and Modbus for electrical equipment",
      "Inverter and meter integration across vendors",
      "Cellular gateways with buffering and remote management",
      "Time-series storage with long retention for seasonal analysis",
      "Alerting with escalation and acknowledgement tracking",
      "Mobile access for field teams",
    ],
    outcomes: [
      "Fault awareness within minutes rather than on the next visit",
      "Underperformance detected against expectation continuously",
      "One view across equipment from different manufacturers",
      "Site visits driven by condition rather than by schedule",
      "Complete data despite unreliable connectivity",
    ],
    services: ["industrial-iot", "edge-computing", "scada-development", "industrial-dashboards", "predictive-maintenance"],
    faq: [
      { q: "Our sites have very poor mobile coverage. Does that make this impractical?", a: "No — it makes local buffering essential, which is a standard part of the design. The gateway stores data locally and back-fills when a connection is available, so an intermittent link produces delayed data rather than missing data. For sites with no coverage at all, scheduled collection over a physical or satellite path is possible." },
      { q: "Can you integrate inverters and meters from different manufacturers?", a: "Yes. Most support Modbus, and many support a documented API. The work is in normalising them to a common model so a portfolio view is meaningful — which is precisely the problem the edge layer exists to solve." },
    ],
  },

  {
    slug: "water-and-wastewater",
    name: "Water & Wastewater",
    short: "Treatment, pumping and distribution",
    title: "SCADA & Monitoring for Water and Wastewater",
    description:
      "SCADA, telemetry and automation for water and wastewater treatment — remote pumping station monitoring, ETP/STP control and compliance reporting.",
    h1: "Water & wastewater",
    lead: "Water systems are geographically distributed, largely unmanned, and subject to compliance reporting. The engineering challenge is remote reliability: assets in places with no staff, no reliable power and no dependable connectivity, that must nevertheless be controllable and evidenced.",
    problems: [
      "Pumping stations checked by physical visit",
      "Failures discovered through overflow or supply complaints",
      "Compliance data compiled manually from logbooks",
      "Chemical dosing adjusted by hand and by judgement",
      "Energy is a dominant cost with no per-asset attribution",
    ],
    solutions: [
      { title: "Remote telemetry and control", body: "Levels, flows, pressures, pump status and faults reported continuously from distributed sites, with supervisory control where appropriate." },
      { title: "Treatment plant automation", body: "ETP and STP control including dosing, aeration and sludge handling, with sequencing and interlocks." },
      { title: "Compliance monitoring and reporting", body: "Continuous quality parameter logging with automatic report generation and an auditable record." },
      { title: "Pump efficiency and condition", body: "Energy per volume pumped, plus vibration and temperature trending on critical pump sets." },
      { title: "Leak and anomaly detection", body: "Flow-balance analysis across the network to identify losses that a periodic audit would not find." },
    ],
    technology: [
      "Level, flow, pressure and analytical instrumentation",
      "PLC and RTU control at distributed sites",
      "Cellular and radio telemetry with local buffering",
      "SCADA with alarm management and escalation",
      "Solar and battery power at remote installations",
      "Automated compliance reporting",
    ],
    outcomes: [
      "Distributed asset status visible continuously",
      "Failures alerted before they become service incidents",
      "Compliance reporting produced from continuous data",
      "Energy per volume pumped measured and improvable",
      "Losses detected through flow reconciliation",
    ],
    services: ["scada-development", "industrial-automation", "industrial-iot", "edge-computing", "predictive-maintenance"],
    faq: [
      { q: "Can remote sites work without mains power?", a: "Yes. Solar with battery backup is standard for remote telemetry installations, and the instrumentation and RTU are specified for the available power budget. The design constraint is usually how often data is transmitted, which is a trade-off we size explicitly rather than assume." },
      { q: "Can this run an ETP or STP automatically?", a: "Automation of dosing, aeration and sludge handling is well established and reduces the variation that comes from manual adjustment. Full unattended operation depends on the process, the variability of the incoming load and the regulatory position, and we are direct about what should remain supervised." },
    ],
  },

  {
    slug: "logistics-and-warehousing",
    name: "Logistics & Warehousing",
    short: "Warehouses, cold storage and distribution",
    title: "Monitoring & Automation for Warehousing and Logistics",
    description:
      "Monitoring and automation for warehouses and cold storage — conveyor and sortation integration, cold chain monitoring, and material handling visibility.",
    h1: "Logistics & warehousing",
    lead: "Warehouses are increasingly automated but rarely well instrumented. Conveyors, sorters and material handling equipment produce useful data that is almost never captured, and cold storage carries a continuous compliance obligation that is often met with a clipboard.",
    problems: [
      "Conveyor and sortation stoppages are frequent and unrecorded",
      "Cold storage temperature is checked on rounds, not monitored",
      "Throughput is known daily but not by hour or by zone",
      "Equipment faults are reported verbally and response is unmeasured",
      "Energy use in refrigeration is a major cost with no attribution",
    ],
    solutions: [
      { title: "Material handling equipment monitoring", body: "State, throughput, jam and fault capture across conveyors, sorters and lifts, with the true constraint made visible." },
      { title: "Cold chain monitoring", body: "Continuous temperature and humidity logging across chambers, docks and vehicles, with alerting and an auditable record." },
      { title: "Throughput and zone analytics", body: "Volume by hour, zone and shift, so labour planning is based on measurement rather than on the previous week's impression." },
      { title: "Refrigeration monitoring", body: "Compressor and plant room monitoring with energy attribution and condition-based maintenance." },
      { title: "Maintenance workflow", body: "Automatic fault alerting with escalation and measured response, replacing verbal reporting." },
    ],
    technology: [
      "PLC reads from conveyor and sortation controllers",
      "Wireless temperature and humidity sensors for chambers",
      "Energy meters on refrigeration plant",
      "Barcode and RFID integration where present",
      "Mobile alerting for maintenance teams",
      "Dashboards by zone, hour and shift",
    ],
    outcomes: [
      "Equipment downtime measured rather than estimated",
      "Cold chain evidenced continuously",
      "Throughput visible by hour and zone",
      "Refrigeration energy attributable and reducible",
      "Fault response time measured",
    ],
    services: ["machine-monitoring", "industrial-iot", "industrial-mobile-apps", "industrial-dashboards", "system-integration"],
    faq: [
      { q: "Can you monitor temperature in vehicles as well as chambers?", a: "Yes, using cellular loggers with local storage that report on a schedule and back-fill when a connection is available. The record is continuous even where coverage is not, which is what a compliance record requires." },
      { q: "Our conveyor system is from a single supplier who controls the software. Can we still get data?", a: "Usually yes, by reading from the controller rather than the supplier's application, or through whatever interface the system exposes. We approach this with the supplier where possible, since an integration they know about is one they will not break at the next update." },
    ],
  },

  {
    slug: "oem-and-machine-builders",
    name: "OEM & Machine Builders",
    short: "Machine manufacturers and equipment suppliers",
    title: "Connected Machines for OEMs and Machine Builders",
    description:
      "IoT and software for machine builders — connected machine platforms, remote monitoring and support, and white-label dashboards for your customers.",
    h1: "OEM & machine builders",
    lead: "If you build machines, your customers are increasingly asking whether they can be monitored — and your service organisation is spending money sending engineers to diagnose faults that could have been identified remotely. Connectivity turns both of those into an advantage rather than a cost.",
    problems: [
      "Customers are asking for connectivity that the machine cannot currently provide",
      "Service engineers travel to diagnose problems that are visible in the data",
      "No visibility of how machines behave in the field after commissioning",
      "Warranty claims cannot be assessed against actual operating conditions",
      "Competitors are shipping connected machines and it is affecting tenders",
    ],
    solutions: [
      { title: "Connected machine platform", body: "A standard connectivity and data package designed into your machine, so every unit shipped is monitorable from the first day." },
      { title: "Remote diagnostics and support", body: "Secure remote access to machine data and, where appropriate, to the controller — so a large share of service calls are resolved without travel." },
      { title: "White-label customer dashboards", body: "A monitoring portal branded as yours, giving your customers visibility and giving you an ongoing relationship after the sale." },
      { title: "Fleet analytics", body: "Aggregate data across all installed machines, informing design decisions with how equipment is actually used rather than how it was expected to be." },
      { title: "Service and warranty data", body: "Operating conditions, duty cycle and fault history available when a warranty claim is assessed." },
    ],
    technology: [
      "Embedded or DIN-rail gateway designed into the machine",
      "Secure remote access with per-customer isolation and audit",
      "Multi-tenant cloud platform with role separation",
      "Fleet-level analytics and comparison",
      "Branded web and mobile interfaces",
      "Provisioning workflow so commissioning is a scan, not a project",
    ],
    outcomes: [
      "Connectivity as a standard machine feature",
      "A measurable share of service calls resolved remotely",
      "Field behaviour visible for design and reliability work",
      "Warranty assessed against actual operating data",
      "A recurring service offering alongside machine sales",
    ],
    services: ["industrial-iot", "edge-computing", "custom-industrial-software", "industrial-mobile-apps", "plc-programming"],
    faq: [
      { q: "Our customers are concerned about their data being visible to us.", a: "That concern is reasonable and the platform must be designed around it. Per-customer isolation, explicit consent for what the OEM can see, auditable access, and the ability for the customer to run entirely on their own infrastructure are all standard design options. Being explicit about this in your sales conversation usually turns it from an objection into a differentiator." },
      { q: "Can this be white-labelled as our own product?", a: "Yes — that is the usual arrangement for machine builders. The interface, the domain and the branding are yours. We build and maintain the platform behind it, either as a development engagement you then own, or on an ongoing basis. Both work; which is better depends on whether you want to carry the software capability internally." },
    ],
  },
];

export const industrySlugs = industries.map((i) => i.slug);

export function getIndustry(slug: string): Industry | undefined {
  return industries.find((i) => i.slug === slug);
}
